spring:
  application:
    name: spike-system

  # 模板引擎配置：
  thymeleaf:
    cache: false  # 关闭thymeleaf模板引擎的缓存

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spike_system_db?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root

    # 数据库连接池
    hikari:
      # 连接池名称：
      pool-name: DataHikariCP
      # 最小空闲连接：
      minimum-idle: 5
      # 空闲连接存活最大时间，默认10分钟：
      idle-timeout: 180000
      # 从连接池返回的连接自动提交：
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认30分钟：
      max-lifetime: 180000
      # 连接超时时间，默认30秒：
      connection-timeout: 30000
      # 测试连接是否可用的查询语句：
      connection-init-sql: SELECT 1

# mybatis-plus 配置：
mybatis-plus:
  # 配置Mapper.xml映射文件：
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 返回值别名：
  type-aliases-package: com.krian.spike.pojo

# MyBatis SQL打印（方法接口所在包，不是Mapper.xml所在的包）
logging:
  level:
    com.krian.spike.mapper: debug